# Generated by Django 2.0.5 on 2018-08-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180815_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chartset',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='day_of_month',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='graph',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='week',
            field=models.CharField(default='01', max_length=10),
        ),
        migrations.AlterField(
            model_name='graph',
            name='year',
            field=models.CharField(default='2018', max_length=10),
        ),
    ]
