# Generated by Django 2.0.5 on 2018-05-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180524_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='gender',
            field=models.CharField(default='all', max_length=6),
            preserve_default=False,
        ),
    ]
