# Generated by Django 2.0.5 on 2018-08-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180815_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='month',
            field=models.CharField(default='January', max_length=10),
        ),
        migrations.AlterField(
            model_name='graph',
            name='time',
            field=models.CharField(default='0630', max_length=10),
        ),
    ]
