# Generated by Django 2.0.5 on 2018-08-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180815_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='day_of_month',
            field=models.CharField(default='1', max_length=500),
        ),
        migrations.AlterField(
            model_name='graph',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=500),
        ),
        migrations.AlterField(
            model_name='graph',
            name='end_date',
            field=models.DateTimeField(default='2018-01-01', max_length=500),
        ),
        migrations.AlterField(
            model_name='graph',
            name='facility',
            field=models.CharField(default='rec', max_length=100),
        ),
        migrations.AlterField(
            model_name='graph',
            name='gender',
            field=models.CharField(default='rec', max_length=500),
        ),
        migrations.AlterField(
            model_name='graph',
            name='label',
            field=models.CharField(default='set', max_length=60),
        ),
        migrations.AlterField(
            model_name='graph',
            name='month',
            field=models.CharField(default='January', max_length=500),
        ),
        migrations.AlterField(
            model_name='graph',
            name='time',
            field=models.CharField(default='0630', max_length=500),
        ),
        migrations.AlterField(
            model_name='graph',
            name='week',
            field=models.CharField(default='01', max_length=500),
        ),
        migrations.AlterField(
            model_name='graph',
            name='year',
            field=models.CharField(default='2018', max_length=500),
        ),
    ]
