# Generated by Django 2.0.5 on 2018-05-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180524_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['value']},
        ),
    ]
