# Generated by Django 2.0.5 on 2018-08-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20180815_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chart',
            name='type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='area',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='facility',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='gender',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='data',
            name='key',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateTimeField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='date',
            name='day_of_month',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='date',
            name='day_of_week',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='date',
            name='month',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='date',
            name='week',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='date',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
