# Generated by Django 2.0.5 on 2018-05-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20180524_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='week',
            field=models.CharField(max_length=3),
        ),
    ]
