# Generated by Django 2.0.5 on 2018-08-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20180815_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
