# Generated by Django 2.0.5 on 2018-05-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20180525_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='area',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='day_of_month',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='data',
            name='day_of_week',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='data',
            name='facility',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='gender',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='data',
            name='month',
            field=models.CharField(max_length=3),
        ),
    ]
