# Generated by Django 2.0.5 on 2018-05-25 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20180525_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('week', models.CharField(max_length=3)),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=3)),
                ('day_of_week', models.CharField(max_length=4)),
                ('day_of_month', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='day_of_month',
        ),
        migrations.RemoveField(
            model_name='data',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='data',
            name='month',
        ),
        migrations.RemoveField(
            model_name='data',
            name='week',
        ),
        migrations.RemoveField(
            model_name='data',
            name='year',
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Date'),
        ),
    ]
