# Generated by Django 2.0.5 on 2019-01-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20180815_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='data',
        ),
        migrations.AlterField(
            model_name='graph',
            name='data_json',
            field=models.CharField(default='-', max_length=1000000),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
