# Generated by Django 2.0.5 on 2019-02-04 14:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20190115_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='data_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={''}),
        ),
    ]
