# Generated by Django 2.0.5 on 2018-05-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20180525_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
