# Generated by Django 2.0.5 on 2018-06-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20180525_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('label', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChartSet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataToGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('color', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Chart')),
            ],
        ),
        migrations.AddField(
            model_name='datatograph',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Graph'),
        ),
        migrations.AddField(
            model_name='datatograph',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ChartData'),
        ),
        migrations.AddField(
            model_name='chart',
            name='chart_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ChartSet'),
        ),
    ]
