# Generated by Django 2.2.4 on 2019-08-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20190204_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
