# Generated by Django 2.0.5 on 2018-06-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20180601_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartdata',
            name='color',
            field=models.ManyToManyField(related_name='DataToGraph', to='pages.Graph'),
        ),
        migrations.AddField(
            model_name='graph',
            name='label',
            field=models.ManyToManyField(related_name='DataToGraph', to='pages.ChartData'),
        ),
    ]
