# Generated by Django 2.0.5 on 2018-06-01 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20180601_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartdata',
            name='color',
        ),
        migrations.AddField(
            model_name='data',
            name='label',
            field=models.ManyToManyField(related_name='DataToGraph', to='pages.Graph'),
        ),
        migrations.AlterField(
            model_name='datatograph',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Data'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='label',
            field=models.ManyToManyField(related_name='DataToGraph', to='pages.Data'),
        ),
        migrations.DeleteModel(
            name='ChartData',
        ),
    ]
