# Generated by Django 2.0.5 on 2018-06-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20180601_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='id',
            new_name='key',
        ),
    ]
