# Generated by Django 2.0.5 on 2018-06-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20180601_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='label',
            field=models.ManyToManyField(to='pages.Graph'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='label',
            field=models.ManyToManyField(to='pages.Data'),
        ),
    ]
