# Generated by Django 2.0.5 on 2018-06-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20180601_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='label',
        ),
    ]
