# Generated by Django 2.0.5 on 2018-06-01 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_data_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatograph',
            old_name='label',
            new_name='data_label',
        ),
        migrations.RenameField(
            model_name='datatograph',
            old_name='color',
            new_name='graph_id',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='color',
            new_name='id',
        ),
    ]
