# Generated by Django 2.0.5 on 2018-06-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20180601_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatograph',
            name='data_label',
        ),
        migrations.RemoveField(
            model_name='datatograph',
            name='graph_id',
        ),
        migrations.AlterField(
            model_name='graph',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='DataToGraph',
        ),
    ]
