# Generated by Django 2.0.5 on 2018-06-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20180601_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainset',
            name='data',
        ),
        migrations.RemoveField(
            model_name='datainset',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='data',
        ),
        migrations.AddField(
            model_name='graph',
            name='color',
            field=models.CharField(default='red', max_length=25),
        ),
        migrations.DeleteModel(
            name='DataInSet',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
    ]
