# Generated by Django 2.0.5 on 2018-06-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20180604_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainset',
            name='data',
        ),
        migrations.RemoveField(
            model_name='datainset',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='data',
        ),
        migrations.AlterField(
            model_name='datainset',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
