# Generated by Django 2.0.5 on 2018-06-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20180604_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataInSet',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
    ]
