# Generated by Django 2.0.5 on 2018-06-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20180604_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='label',
            new_name='data',
        ),
    ]
