# Generated by Django 2.0.5 on 2018-06-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20180604_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='label',
            field=models.CharField(default='set', max_length=40),
        ),
    ]
