# Generated by Django 2.0.5 on 2018-06-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_graph_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='unit',
            field=models.CharField(default='hour', max_length=15),
        ),
    ]
