# Generated by Django 2.0.5 on 2018-06-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_graph_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='area',
            field=models.CharField(default='str', max_length=20),
        ),
        migrations.AddField(
            model_name='graph',
            name='end_date',
            field=models.DateTimeField(default='2018-01-01 00:00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='graph',
            name='facility',
            field=models.CharField(default='rec', max_length=20),
        ),
        migrations.AddField(
            model_name='graph',
            name='gender',
            field=models.CharField(default='rec', max_length=20),
        ),
        migrations.AddField(
            model_name='graph',
            name='month',
            field=models.CharField(default='January', max_length=2),
        ),
        migrations.AddField(
            model_name='graph',
            name='start_date',
            field=models.DateTimeField(default='2018-01-01 00:00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='graph',
            name='week',
            field=models.CharField(default='1', max_length=4),
        ),
        migrations.AddField(
            model_name='graph',
            name='year',
            field=models.IntegerField(default='2018', max_length=4),
        ),
    ]
