# Generated by Django 2.0.5 on 2018-06-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20180604_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='day_of_month',
            field=models.CharField(default='1', max_length=4),
        ),
        migrations.AddField(
            model_name='graph',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=20),
        ),
        migrations.AddField(
            model_name='graph',
            name='time',
            field=models.CharField(default='0630', max_length=5),
        ),
    ]
