# Generated by Django 2.0.5 on 2018-06-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20180604_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='type',
            field=models.CharField(default='line', max_length=10),
        ),
        migrations.AlterField(
            model_name='graph',
            name='area',
            field=models.CharField(default='strength', max_length=20),
        ),
        migrations.AlterField(
            model_name='graph',
            name='color',
            field=models.CharField(default='rgb(255, 0, 0, .3', max_length=25),
        ),
        migrations.AlterField(
            model_name='graph',
            name='end_date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='graph',
            name='start_date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='graph',
            name='week',
            field=models.CharField(default='01', max_length=4),
        ),
        migrations.AlterField(
            model_name='graph',
            name='year',
            field=models.CharField(default='2018', max_length=4),
        ),
    ]
