# Generated by Django 2.0.5 on 2018-06-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20180608_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='end_date',
            field=models.DateTimeField(max_length=20),
        ),
        migrations.AlterField(
            model_name='graph',
            name='start_date',
            field=models.DateTimeField(max_length=20),
        ),
    ]
