# Generated by Django 2.0.5 on 2018-06-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_chartset_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartset',
            name='id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
