# Generated by Django 2.0.5 on 2018-06-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_auto_20180611_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartset',
            name='name',
            field=models.CharField(default='unsaved', max_length=60),
        ),
    ]
