# Generated by Django 2.0.5 on 2018-06-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_auto_20180612_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='end_date',
            field=models.DateTimeField(default='2018-01-01', max_length=20),
        ),
        migrations.AlterField(
            model_name='graph',
            name='start_date',
            field=models.DateTimeField(default='2018-01-01', max_length=20),
        ),
    ]
