# Generated by Django 2.0.5 on 2018-07-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20180615_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='estimated',
            field=models.BooleanField(default=False),
        ),
    ]
