# Generated by Django 2.0.5 on 2018-07-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_data_estimated'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='data_json',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
