# Generated by Django 2.0.5 on 2018-08-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_graph_data_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={},
        ),
        migrations.AlterField(
            model_name='chart',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chartset',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateTimeField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
