# Generated by Django 2.0.5 on 2018-08-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_auto_20180807_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chart',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chart',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chart',
            name='type',
            field=models.CharField(default='line', max_length=10),
        ),
        migrations.AlterField(
            model_name='chartset',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chartset',
            name='name',
            field=models.CharField(default='unsaved', max_length=60),
        ),
        migrations.AlterField(
            model_name='chartset',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='area',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='estimated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='facility',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='gender',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='data',
            name='key',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='date',
            name='day_of_month',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='date',
            name='day_of_week',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='date',
            name='month',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='date',
            name='week',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='date',
            name='year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='graph',
            name='area',
            field=models.CharField(default='strength', max_length=20),
        ),
        migrations.AlterField(
            model_name='graph',
            name='color',
            field=models.CharField(default='rgb(255, 0, 0, .3', max_length=25),
        ),
        migrations.AlterField(
            model_name='graph',
            name='data',
            field=models.ManyToManyField(to='pages.Data'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='data_json',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='graph',
            name='day_of_month',
            field=models.CharField(default='1', max_length=4),
        ),
        migrations.AlterField(
            model_name='graph',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=20),
        ),
        migrations.AlterField(
            model_name='graph',
            name='end_date',
            field=models.DateTimeField(default='2018-01-01', max_length=20),
        ),
        migrations.AlterField(
            model_name='graph',
            name='facility',
            field=models.CharField(default='rec', max_length=20),
        ),
        migrations.AlterField(
            model_name='graph',
            name='gender',
            field=models.CharField(default='rec', max_length=20),
        ),
        migrations.AlterField(
            model_name='graph',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='label',
            field=models.CharField(default='set', max_length=40),
        ),
        migrations.AlterField(
            model_name='graph',
            name='month',
            field=models.CharField(default='January', max_length=2),
        ),
        migrations.AlterField(
            model_name='graph',
            name='start_date',
            field=models.DateTimeField(default='2018-01-01', max_length=20),
        ),
        migrations.AlterField(
            model_name='graph',
            name='time',
            field=models.CharField(default='0630', max_length=5),
        ),
        migrations.AlterField(
            model_name='graph',
            name='unit',
            field=models.CharField(default='hour', max_length=15),
        ),
        migrations.AlterField(
            model_name='graph',
            name='week',
            field=models.CharField(default='01', max_length=4),
        ),
        migrations.AlterField(
            model_name='graph',
            name='year',
            field=models.CharField(default='2018', max_length=4),
        ),
    ]
