# Generated by Django 2.0.5 on 2018-08-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_auto_20180807_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='chart_set',
        ),
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='chart',
        ),
        migrations.AlterField(
            model_name='chart',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chartset',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateTimeField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
